### PR TITLE
Use the configured proxy host and port for the download

### LINKED ISSUE #14: Proxy is not used for downloading binaries
When providing a proxy host and port I would expect that the download would also use the proxy settings, but it isn't.

### PR DESCRIPTION
**Pull request by mohlendo**
Sadly for https download over proxy, we need a special http agent implementation. Added a simple one, too.

Fixes #14

### CODE REVIEW

**Comment by nidhimj22** [comment]
@mohlendo  Can you please fix the tests?

**Comment by mohlendo** [comment]
@nidhimj22 I have fixed the test. But the error wasn't related to my changes - should have been there before...

**Comment by nidhimj22** [comment]
@mohlendo Thanks! Can you also write a test case for this? You can mock the proxy.

**Comment by tr4n2uil** [comment]
Awesomeness! Thanks @mohlendo

**Pull request merged**
