### PR TITLE
Add TypeScript definition file

### LINKED ISSUE #37: TypeScript definition file
Hi there!

Would you accept a PR for a TypeScript definition file?

If you're not interested in this being part of this repository, I'm happy to contribute it to https://github.com/DefinitelyTyped/DefinitelyTyped instead.

The definition file I have locally looks like this:

```typescript
declare module 'browserstack-local' {
  interface Options {
    key: string
    verbose: boolean
    force: boolean
    only: string
    onlyAutomate: boolean
    forceLocal: boolean
    localIdentifier: string
    folder: string
    proxyHost: string
    proxyPort: string
    proxyUser: string
    proxyPass: string
    forceProxy: boolean
    logFile: string
    parallelRuns: string
    binarypath: string
    [key: string]: string | boolean
  }

  class Local {
    start(options: Partial<Options>, callback: () => void): void
    isRunning(): boolean
    stop(callback: () => void): void
  }
}
```

### PR DESCRIPTION
**Pull request by jlfwong**
Fixes #37

### CODE REVIEW

**Comment by patrick91** [comment]
@jlfwong thanks for this, I copied it to my project and did some changes, if you need them:

```ts
declare module "browserstack-local" {
  interface Options {
    key: string;
    verbose: boolean;
    force: boolean;
    only: string;
    onlyAutomate: boolean;
    forceLocal: boolean;
    localIdentifier: string;
    folder: string;
    proxyHost: string;
    proxyPort: string;
    proxyUser: string;
    proxyPass: string;
    forceProxy: boolean;
    logFile: string;
    parallelRuns: string;
    binarypath: string;
    [key: string]: string | boolean;
  }

  class Local {
    start(options: Partial<Options>, callback: (error: Error) => void): void;
    isRunning(): boolean;
    stop(callback?: () => void): void;
  }
}
```

I've just made the stop callback optional and added the error param to the start callback

**Comment by Simsteve7** [comment]
Why is the TypeScript definition file still not merged in?

**Comment by thasmo** [comment]
Please!

**Comment by pulkitsharma07** [comment]
Thanks @jlfwong

**Pull request merged**
